name: shopping_ui
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^1.3.1
  flutter_icons: ^1.1.0
  cloud_firestore: ^3.3.0
  firebase_storage: ^10.3.2
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.7.0
  google_maps_flutter: ^2.1.8
  geolocator: ^7.4.0
  bootpay: ^4.2.5

  flutter_naver_login: ^1.6.0

  kakao_flutter_sdk: ^1.2.1
  
  google_sign_in: ^5.4.0
  firebase_auth: ^3.5.0
  flutter_facebook_auth: ^4.4.0+1

  launch_review: ^3.0.1  

  remedi_kopo: ^0.0.1

  http: ^0.13.4
  flutter_svg: ^1.1.1+1  
  form_field_validator: ^1.1.0  
  flutter_bcrypt: ^1.0.7
  shared_preferences: ^2.0.15

  dio: ^4.0.6
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.3
  file_picker: ^5.0.0
  path_provider: ^2.0.11

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/temp/
    - assets/images/raster/.
    - assets/images/vector/.
    - assets/images/animation/.
    - assets/images/raster/ori blind forest/.
    - assets/images/raster/rayman legends/.    
    
